// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"tinamic/handler"
	"tinamic/repository"
	"tinamic/service"
)

// Injectors from wire.go:

func InitializeUserService() *handler.UserHandler {
	userRepository := repository.NewUserRepository()
	userService := service.NewUserService(userRepository)
	userHandler := handler.NewUserHandler(userService)
	return userHandler
}

func InitializeDataSourceService() *handler.DataSourceHandler {
	dataSourceRepository := repository.NewDataSourceRepository()
	dataSourceService := service.NewDataSourceService(dataSourceRepository)
	dataSourceHandler := handler.NewDataSourceHandler(dataSourceService)
	return dataSourceHandler
}
